export GIT_BYPASS = 0

# Define Firmware Version Number
export PRJ_VERSION = 0xCEC83100

# Define target part
export PRJ_PART = XC7A200TFFG1156-3

# Define target output
target: prom

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk
